//! The freestanding headers and the kernel library.
//!
//! §22 asks for six things in a freestanding environment: *kernel headers*, *startup
//! objects*, *linker layout*, *compiler runtime support*, *LZA ABI support*, *device
//! headers* and a *low-level runtime*. The sysroot had the first two and part of the
//! fourth, and the other three did not exist.
//!
//! # Why these are generated and not written out
//!
//! `lazos/abi.h` and `lazos/syscall.h` were already generated, from
//! `lazalith_os_abi::ABI_SYSCALLS`, and the reason is worth repeating because it is the
//! reason the rest are generated too: **a hand-written copy of a header that describes a
//! table is a second place for the table to live, and the second place is the one that
//! will be wrong.** A `lazos/syscall.h` written by hand and an `ABI_SYSCALLS` that gains a
//! syscall would disagree, and the disagreement is a call that reads the wrong register —
//! a bug with no message, in a kernel, at run time.
//!
//! The freestanding headers here are generated for a different reason: **they are the
//! compiler's, not the library's.** `stddef.h`, `stdint.h` and `stdbool.h` are the headers
//! C says a freestanding implementation must provide, and their contents follow from the
//! target's word width and pointer width — which are already known here and are the same
//! two numbers every other part of the target side uses.
//!
//! # What a freestanding kernel does *not* get
//!
//! No `string.h`, no `stdio.h`, no `malloc`. A freestanding environment has no heap, no
//! files and no buffered output, and a header that declared `fopen` would be a promise the
//! environment cannot keep. What it gets instead is [`KERNEL_LIBRARY`]: `memcpy`, `memset`
//! and the handful of byte functions a kernel cannot boot without, and a console that goes
//! straight to the console device through the ABI.

/// The freestanding standard headers, as `(name, text)`.
///
/// **Written in the order a kernel includes them, and each is self-contained.** There is
/// no include between them, so a kernel can take `stdint.h` alone and get a working
/// `uint64_t` with nothing else in the build.
pub fn freestanding_headers(word_bits: u32) -> Vec<(&'static str, String)> {
    vec![
        ("stddef.h", stddef_header(word_bits)),
        ("stdint.h", stdint_header(word_bits)),
        ("stdbool.h", stdbool_header()),
    ]
}

/// `<stddef.h>`: the sizes and the null pointer.
///
/// **`size_t` is the target's word, not `unsigned long`,** because the whole point of a
/// freestanding environment is that the C library's idea of these types is not available
/// and the language's own types must be enough. On both of Lazalith's targets a pointer
/// and a `size_t` are one word wide, and the header says so with `__LAZALITH_WORD_BITS__`
/// so that a program can see it without guessing.
fn stddef_header(word_bits: u32) -> String {
    format!(
        "/* The freestanding <stddef.h>.\n\
         *\n\
         * GENERATED by `lazalith-sysroot`. Do not edit.\n\
         *\n\
         * A freestanding environment has no C library, so the language's own types are\n\
         * the only types a program can rely on. This header therefore defines nothing\n\
         * that needs a library, and nothing that a hosted environment would define\n\
         * differently for a *given target* — a hosted <stddef.h> on this target would\n\
         * say the same things.\n\
         */\n\
         \n\
         #ifndef LAZALITH_STDDEF_H\n\
         #define LAZALITH_STDDEF_H\n\
         \n\
         #define __LAZALITH_WORD_BITS__ {word_bits}\n\
         \n\
         typedef unsigned long size_t;\n\
         typedef long ptrdiff_t;\n\
         typedef unsigned long wchar_t;\n\
         \n\
         #ifndef NULL\n\
         #define NULL 0\n\
         #endif\n\
         \n\
         #define offsetof(type, member) ((unsigned long)&(((type *)0)->member))\n\
         \n\
         #endif\n"
    )
}

/// `<stdint.h>`: the exact-width types, for a machine that has them.
///
/// **The names are the C standard's, and the widths are the target's.** `int8_t` is eight
/// bits because the target has an eight-bit byte, not because the header chose eight; the
/// header is generated from the target so that a future 16-bit-byte target gets
/// `int16_t` where this one gets `int8_t` without anything being edited by hand.
fn stdint_header(word_bits: u32) -> String {
    let (word, uword, lword, ulword) = if word_bits == 32 {
        ("int", "unsigned int", "long", "unsigned long")
    } else {
        ("long", "unsigned long", "long", "unsigned long")
    };
    let max_uword = if word_bits == 32 {
        "0xffffffffu"
    } else {
        "0xffffffffffffffffu"
    };
    format!(
        "/* The freestanding <stdint.h>.\n\
         *\n\
         * GENERATED by `lazalith-sysroot`. Do not edit.\n\
         *\n\
         * A freestanding environment has no <limits.h> and no <inttypes.h>, so the\n\
         * limits a kernel needs are here. The exact-width types exist because the\n\
         * target has fixed widths: there is no `char` whose size is a guess.\n\
         */\n\
         \n\
         #ifndef LAZALITH_STDINT_H\n\
         #define LAZALITH_STDINT_H\n\
         \n\
         typedef signed char int8_t;\n\
         typedef unsigned char uint8_t;\n\
         typedef signed short int16_t;\n\
         typedef unsigned short uint16_t;\n\
         typedef signed {word} int32_t;\n\
         typedef unsigned {uword} uint32_t;\n\
         typedef signed {lword} int64_t;\n\
         typedef unsigned {ulword} uint64_t;\n\
         \n\
         typedef signed char int_least8_t;\n\
         typedef unsigned char uint_least8_t;\n\
         typedef signed short int_least16_t;\n\
         typedef unsigned short uint_least16_t;\n\
         typedef signed {lword} int_least32_t;\n\
         typedef unsigned {ulword} uint_least32_t;\n\
         \n\
         typedef signed {lword} int_fast8_t;\n\
         typedef unsigned {ulword} uint_fast8_t;\n\
         typedef signed {lword} int_fast16_t;\n\
         typedef unsigned {ulword} uint_fast16_t;\n\
         typedef signed {lword} int_fast32_t;\n\
         typedef unsigned {ulword} uint_fast32_t;\n\
         \n\
         typedef unsigned long intptr_t;\n\
         typedef unsigned long uintptr_t;\n\
         typedef long intmax_t;\n\
         typedef unsigned long uintmax_t;\n\
         \n\
         #define INT8_MIN (-128)\n\
         #define INT8_MAX 127\n\
         #define UINT8_MAX 255\n\
         #define INT16_MIN (-32768)\n\
         #define INT16_MAX 32767\n\
         #define UINT16_MAX 65535\n\
         #define INT32_MIN (-2147483647 - 1)\n\
         #define INT32_MAX 2147483647\n\
         #define UINT32_MAX 4294967295u\n\
         #define INT64_MAX 9223372036854775807L\n\
         #define UINT64_MAX 18446744073709551615uL\n\
         \n\
         #define SIZE_MAX {max_uword}\n\
         #define PTRDIFF_MIN (-{max_uword} - 1)\n\
         #define PTRDIFF_MAX {max_uword}\n\
         \n\
         #ifndef INT64_C\n\
         #define INT64_C(value) value##L\n\
         #define UINT64_C(value) value##uL\n\
         #endif\n\
         \n\
         #endif\n"
    )
}

/// `<stdbool.h>`: three macros, and the C one is `1`.
///
/// **A freestanding header because C says it is one, and it is three lines because that
/// is all a language with no `bool` keyword needs.** `bool`, `true` and `false` as macros
/// over `_Bool` is the standard's own solution, and a kernel that wants a boolean type has
/// one without a library.
fn stdbool_header() -> String {
    String::from(
        "/* The freestanding <stdbool.h>.\n\
         *\n\
         * GENERATED by `lazalith-sysroot`. Do not edit.\n\
         */\n\
         \n\
         #ifndef LAZALITH_STDBOOL_H\n\
         #define LAZALITH_STDBOOL_H\n\
         \n\
         #define bool _Bool\n\
         #define true 1\n\
         #define false 0\n\
         #define __bool_true_false_are_defined 1\n\
         \n\
         #endif\n",
    )
}

/// The kernel library: the freestanding C library, as text.
///
/// **In the same crate as the hosted one, and for the same reason.** `lazalith-c-runtime`
/// is C source in a Rust crate rather than a compiled `.lzo` because *a library that is
/// generated code is a library that can disagree with the compiler about what the language
/// means*. Every line of `memcpy` below goes through the same lexer, parser, resolver,
/// type checker and code generator as a kernel's own code, so a bug in it is a bug anyone
/// can point at in a file anyone can read.
///
/// What is here is the minimum a kernel cannot boot without, and what is *not* here is the
/// point: no `printf` (no variadic definitions, §21's list of what a kernel does not get),
/// no `malloc` (a freestanding environment has no heap and a bump allocator over an
/// `allocate_memory` syscall is a user-space convenience, not a kernel one), and no
/// `fopen` (a handle travels in a register the calling convention has no room for).
///
/// The console functions are the low-level runtime §22 asks for, and they go **straight to
/// the device through the ABI** — one character, no buffering, no allocation — because a
/// kernel that cannot print is a kernel whose bugs are invisible.
pub const KERNEL_LIBRARY: &str = r#"/* The freestanding C library for a Lazalith kernel.
 *
 * GENERATED into a sysroot by `lazalith-sysroot`. Do not edit: this text goes through
 * the same front end as everything else, and a hand-edited copy in a sysroot would be a
 * copy nobody compiles.
 *
 * There is no heap here, no buffering and no formatted output. What a kernel cannot boot
 * without is `memcpy`, `memset` and a console, and those are what this is.
 */

#ifndef LAZALITH_KERNEL_LIBRARY
#define LAZALITH_KERNEL_LIBRARY

/* The byte functions. A kernel copies structures around before it has any of its own
 * memory management, so these are the first thing anything needs. */

void *memcpy(void *destination, const void *source, unsigned long length) {
    unsigned char *to = (unsigned char *)destination;
    const unsigned char *from = (const unsigned char *)source;
    unsigned long index = 0;
    while (index < length) {
        to[index] = from[index];
        index = index + 1;
    }
    return destination;
}

void *memmove(void *destination, const void *source, unsigned long length) {
    unsigned char *to = (unsigned char *)destination;
    const unsigned char *from = (const unsigned char *)source;
    if (to < from) {
        unsigned long index = 0;
        while (index < length) {
            to[index] = from[index];
            index = index + 1;
        }
    } else {
        unsigned long index = length;
        while (index > 0) {
            index = index - 1;
            to[index] = from[index];
        }
    }
    return destination;
}

void *memset(void *destination, int value, unsigned long length) {
    unsigned char *to = (unsigned char *)destination;
    unsigned char byte = (unsigned char)value;
    unsigned long index = 0;
    while (index < length) {
        to[index] = byte;
        index = index + 1;
    }
    return destination;
}

int memcmp(const void *left, const void *right, unsigned long length) {
    const unsigned char *one = (const unsigned char *)left;
    const unsigned char *two = (const unsigned char *)right;
    unsigned long index = 0;
    while (index < length) {
        if (one[index] != two[index]) {
            if (one[index] < two[index]) {
                return -1;
            }
            return 1;
        }
        index = index + 1;
    }
    return 0;
}

unsigned long strlen(const char *text) {
    unsigned long length = 0;
    while (text[length] != 0) {
        length = length + 1;
    }
    return length;
}

/* The console.
 *
 * `write` is an ABI syscall, so this is the device and not a host service: one character,
 * no buffering, no allocation. A kernel that cannot print is a kernel whose bugs are
 * invisible, and a buffered console would need memory the kernel has not built yet.
 */

static int console_error = 0;

int laz_putc(int value) {
    char one[1];
    one[0] = (char)value;
    if (write(1, one, 1) < 0) {
        console_error = 1;
        return -1;
    }
    return value & 255;
}

int laz_puts(const char *text) {
    unsigned long length = strlen(text);
    unsigned long index = 0;
    while (index < length) {
        if (laz_putc((int)text[index]) < 0) {
            return -1;
        }
        index = index + 1;
    }
    return 0;
}

#endif
"#;
