[package]
name = "lazalith-cpu"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
lazalith-types = { path = "../lazalith-types" }
lazalith-isa = { path = "../lazalith-isa" }

[lints]
workspace = true

[dev-dependencies]
lazalith-properties = { path = "../lazalith-properties" }
